// ============================================================================
// 06. TASK PLANNER
// FILE: TaskPlan.cs
// ============================================================================
// This file defines the complete plan with all steps.
//
// PLAN LIFECYCLE:
//
//    ┌─────────────┐
//    │   Created   │ ← Plan created, no steps yet
//    └──────┬──────┘
//           │ AddSteps()
//           ▼
//    ┌─────────────┐
//    │   Planned   │ ← Steps defined, ready for execution
//    └──────┬──────┘
//           │ Execute()
//           ▼
//    ┌─────────────┐
//    │  Executing  │ ← Execution in progress
//    └──────┬──────┘
//           │
//     ┌─────┴─────┐
//     ▼           ▼
// ┌─────────┐ ┌─────────┐
// │Completed│ │ Failed  │
// └─────────┘ └─────────┘
// ============================================================================

namespace TaskPlanner.Planning;

/// <summary>
/// Execution plan states.
/// </summary>
public enum TaskPlanStatus
{
    /// <summary>
    /// Plan created but without steps.
    /// </summary>
    Created,

    /// <summary>
    /// Steps defined, ready for execution.
    /// </summary>
    Planned,

    /// <summary>
    /// Execution in progress.
    /// </summary>
    Executing,

    /// <summary>
    /// All steps completed successfully.
    /// </summary>
    Completed,

    /// <summary>
    /// At least one step failed.
    /// </summary>
    Failed,

    /// <summary>
    /// Execution cancelled by user.
    /// </summary>
    Cancelled
}

/// <summary>
/// Represents a complete execution plan.
///
/// The plan contains:
/// - The user's original objective
/// - The list of steps to execute
/// - The overall plan state
/// - Execution statistics
/// </summary>
public class TaskPlan
{
    // ========================================================================
    // PLAN PROPERTIES
    // ========================================================================

    /// <summary>
    /// Original objective requested by the user.
    /// E.g.: "Create a .NET project with unit tests"
    /// </summary>
    public required string Goal { get; init; }

    /// <summary>
    /// Plan description generated by the agent.
    /// Explains the general approach to be followed.
    /// </summary>
    public string? PlanDescription { get; set; }

    /// <summary>
    /// List of steps to execute.
    /// </summary>
    public List<TaskStep> Steps { get; init; } = new();

    /// <summary>
    /// Current plan state.
    /// </summary>
    public TaskPlanStatus Status { get; set; } = TaskPlanStatus.Created;

    /// <summary>
    /// Plan creation timestamp.
    /// </summary>
    public DateTime CreatedAt { get; init; } = DateTime.UtcNow;

    /// <summary>
    /// Execution start timestamp.
    /// </summary>
    public DateTime? StartedAt { get; set; }

    /// <summary>
    /// Completion timestamp.
    /// </summary>
    public DateTime? CompletedAt { get; set; }

    // ========================================================================
    // COMPUTED PROPERTIES
    // ========================================================================

    /// <summary>
    /// Total number of steps.
    /// </summary>
    public int TotalSteps => Steps.Count;

    /// <summary>
    /// Number of successfully completed steps.
    /// </summary>
    public int CompletedSteps => Steps.Count(s => s.Status == TaskStepStatus.Completed);

    /// <summary>
    /// Number of failed steps.
    /// </summary>
    public int FailedSteps => Steps.Count(s => s.Status == TaskStepStatus.Failed);

    /// <summary>
    /// Number of pending steps.
    /// </summary>
    public int PendingSteps => Steps.Count(s => s.Status == TaskStepStatus.Pending);

    /// <summary>
    /// Completion percentage (0-100).
    /// </summary>
    public int ProgressPercentage =>
        TotalSteps > 0
            ? (int)((CompletedSteps + FailedSteps) * 100.0 / TotalSteps)
            : 0;

    /// <summary>
    /// Currently executing step (if present).
    /// </summary>
    public TaskStep? CurrentStep =>
        Steps.FirstOrDefault(s => s.Status == TaskStepStatus.InProgress);

    /// <summary>
    /// Next step to execute (if present).
    /// </summary>
    public TaskStep? NextStep =>
        Steps.FirstOrDefault(s => s.Status == TaskStepStatus.Pending);

    /// <summary>
    /// Indicates whether all steps have been completed successfully.
    /// </summary>
    public bool AllStepsCompleted =>
        Steps.Count > 0 && Steps.All(s => s.Status == TaskStepStatus.Completed);

    /// <summary>
    /// Indicates whether at least one step has failed.
    /// </summary>
    public bool HasFailures =>
        Steps.Any(s => s.Status == TaskStepStatus.Failed);

    /// <summary>
    /// Total execution duration.
    /// </summary>
    public TimeSpan? Duration =>
        StartedAt.HasValue && CompletedAt.HasValue
            ? CompletedAt.Value - StartedAt.Value
            : StartedAt.HasValue
                ? DateTime.UtcNow - StartedAt.Value
                : null;

    // ========================================================================
    // STEP MANAGEMENT METHODS
    // ========================================================================

    /// <summary>
    /// Adds a step to the plan.
    /// </summary>
    public TaskStep AddStep(string description, string? details = null, string? toolName = null)
    {
        var step = new TaskStep
        {
            Id = Steps.Count + 1,
            Description = description,
            Details = details,
            ToolName = toolName
        };

        Steps.Add(step);

        if (Status == TaskPlanStatus.Created)
        {
            Status = TaskPlanStatus.Planned;
        }

        return step;
    }

    /// <summary>
    /// Adds multiple steps to the plan.
    /// </summary>
    public void AddSteps(IEnumerable<(string description, string? details)> steps)
    {
        foreach (var (description, details) in steps)
        {
            AddStep(description, details);
        }
    }

    // ========================================================================
    // EXECUTION METHODS
    // ========================================================================

    /// <summary>
    /// Starts the execution of the plan.
    /// </summary>
    public void StartExecution()
    {
        if (Status != TaskPlanStatus.Planned)
        {
            throw new InvalidOperationException(
                $"Cannot start execution: plan is in state {Status}");
        }

        Status = TaskPlanStatus.Executing;
        StartedAt = DateTime.UtcNow;
    }

    /// <summary>
    /// Completes the execution of the plan.
    /// </summary>
    public void CompleteExecution()
    {
        CompletedAt = DateTime.UtcNow;
        Status = HasFailures ? TaskPlanStatus.Failed : TaskPlanStatus.Completed;
    }

    /// <summary>
    /// Cancels the execution of the plan.
    /// </summary>
    public void Cancel()
    {
        Status = TaskPlanStatus.Cancelled;
        CompletedAt = DateTime.UtcNow;

        // Mark all pending steps as skipped
        foreach (var step in Steps.Where(s => s.Status == TaskStepStatus.Pending))
        {
            step.Skip("Execution cancelled");
        }
    }

    // ========================================================================
    // VISUALIZATION
    // ========================================================================

    /// <summary>
    /// Generates a textual summary of the plan.
    /// </summary>
    public string GetSummary()
    {
        var lines = new List<string>
        {
            $"📋 Piano: {Goal}",
            $"   Stato: {Status}",
            $"   Progresso: {CompletedSteps}/{TotalSteps} step ({ProgressPercentage}%)"
        };

        if (Duration.HasValue)
        {
            lines.Add($"   Durata: {Duration.Value.TotalSeconds:F1}s");
        }

        return string.Join(Environment.NewLine, lines);
    }

    /// <summary>
    /// Generates the list of steps with status.
    /// </summary>
    public string GetStepList()
    {
        if (Steps.Count == 0)
        {
            return "   (nessuno step definito)";
        }

        return string.Join(Environment.NewLine, Steps.Select(s => $"   {s}"));
    }

    /// <summary>
    /// Generates the complete report of the plan.
    /// </summary>
    public string GetFullReport()
    {
        return $"{GetSummary()}{Environment.NewLine}{Environment.NewLine}Step:{Environment.NewLine}{GetStepList()}";
    }
}
